"""Canonical team name aliases for cross-source matching (ESPN ↔ StatsBomb ↔ Understat).

TODO: expand coverage for MLS (e.g. "LA Galaxy", "Inter Miami"), Saudi Pro League,
      and J-League teams once those sources are integrated.
"""
import re

_ALIASES: dict[str, str] = {
    # England
    "manchester city": "Manchester City",
    "man city": "Manchester City",
    "man. city": "Manchester City",
    "manchester united": "Manchester United",
    "man united": "Manchester United",
    "man utd": "Manchester United",
    "man. united": "Manchester United",
    "tottenham hotspur": "Tottenham Hotspur",
    "spurs": "Tottenham Hotspur",
    "tottenham": "Tottenham Hotspur",
    "wolverhampton wanderers": "Wolverhampton Wanderers",
    "wolves": "Wolverhampton Wanderers",
    "wolverhampton": "Wolverhampton Wanderers",
    "west ham united": "West Ham United",
    "west ham": "West Ham United",
    "newcastle united": "Newcastle United",
    "newcastle": "Newcastle United",
    "brighton & hove albion": "Brighton & Hove Albion",
    "brighton": "Brighton & Hove Albion",
    "sheffield united": "Sheffield United",
    "sheffield utd": "Sheffield United",
    "nottingham forest": "Nottingham Forest",
    "notts forest": "Nottingham Forest",
    "aston villa": "Aston Villa",
    "brentford": "Brentford",
    "fulham": "Fulham",
    "crystal palace": "Crystal Palace",
    "everton": "Everton",
    "chelsea": "Chelsea",
    "arsenal": "Arsenal",
    "liverpool": "Liverpool",
    "leicester city": "Leicester City",
    "leicester": "Leicester City",
    "leeds united": "Leeds United",
    "leeds": "Leeds United",
    "burnley": "Burnley",
    "luton town": "Luton Town",
    "luton": "Luton Town",
    "bournemouth": "Bournemouth",
    "afc bournemouth": "Bournemouth",

    # Spain
    "real madrid": "Real Madrid",
    "fc barcelona": "Barcelona",
    "barcelona": "Barcelona",
    "barca": "Barcelona",
    "atletico madrid": "Atlético Madrid",
    "atletico de madrid": "Atlético Madrid",
    "atlético de madrid": "Atlético Madrid",
    "atletico": "Atlético Madrid",
    "atlético": "Atlético Madrid",
    "sevilla fc": "Sevilla",
    "sevilla": "Sevilla",
    "real sociedad": "Real Sociedad",
    "athletic bilbao": "Athletic Club",
    "athletic club": "Athletic Club",
    "villarreal cf": "Villarreal",
    "villarreal": "Villarreal",
    "real betis": "Real Betis",
    "betis": "Real Betis",
    "valencia cf": "Valencia",
    "valencia": "Valencia",
    "getafe cf": "Getafe",
    "getafe": "Getafe",
    "osasuna": "Osasuna",
    "ca osasuna": "Osasuna",
    "celta vigo": "Celta Vigo",
    "celta de vigo": "Celta Vigo",
    "rayo vallecano": "Rayo Vallecano",
    "girona fc": "Girona",
    "girona": "Girona",

    # Germany
    "bayern munich": "Bayern München",
    "fc bayern munich": "Bayern München",
    "fc bayern münchen": "Bayern München",
    "bayern münchen": "Bayern München",
    "borussia dortmund": "Borussia Dortmund",
    "bvb": "Borussia Dortmund",
    "dortmund": "Borussia Dortmund",
    "bayer leverkusen": "Bayer Leverkusen",
    "leverkusen": "Bayer Leverkusen",
    "rb leipzig": "RB Leipzig",
    "rasenballsport leipzig": "RB Leipzig",
    "borussia mönchengladbach": "Borussia Mönchengladbach",
    "borussia monchengladbach": "Borussia Mönchengladbach",
    "gladbach": "Borussia Mönchengladbach",
    "eintracht frankfurt": "Eintracht Frankfurt",
    "frankfurt": "Eintracht Frankfurt",
    "vfb stuttgart": "VfB Stuttgart",
    "stuttgart": "VfB Stuttgart",
    "sc freiburg": "SC Freiburg",
    "freiburg": "SC Freiburg",
    "union berlin": "1. FC Union Berlin",
    "1. fc union berlin": "1. FC Union Berlin",
    "wolfsburg": "VfL Wolfsburg",
    "vfl wolfsburg": "VfL Wolfsburg",
    "hoffenheim": "TSG Hoffenheim",
    "tsg hoffenheim": "TSG Hoffenheim",
    "werder bremen": "Werder Bremen",

    # Italy
    "juventus": "Juventus",
    "juve": "Juventus",
    "inter milan": "Internazionale",
    "inter": "Internazionale",
    "internazionale": "Internazionale",
    "fc internazionale milano": "Internazionale",
    "ac milan": "Milan",
    "milan": "Milan",
    "as roma": "Roma",
    "roma": "Roma",
    "ss lazio": "Lazio",
    "lazio": "Lazio",
    "ssc napoli": "Napoli",
    "napoli": "Napoli",
    "atalanta bc": "Atalanta",
    "atalanta": "Atalanta",
    "acf fiorentina": "Fiorentina",
    "fiorentina": "Fiorentina",
    "torino fc": "Torino",
    "torino": "Torino",
    "bologna fc": "Bologna",
    "bologna": "Bologna",
    "ac monza": "Monza",
    "monza": "Monza",
    "udinese": "Udinese",
    "hellas verona": "Hellas Verona",
    "verona": "Hellas Verona",
    "us sassuolo": "Sassuolo",
    "sassuolo": "Sassuolo",
    "empoli fc": "Empoli",
    "empoli": "Empoli",

    # France
    "paris saint-germain": "Paris Saint-Germain",
    "paris saint germain": "Paris Saint-Germain",
    "psg": "Paris Saint-Germain",
    "paris sg": "Paris Saint-Germain",
    "olympique de marseille": "Marseille",
    "marseille": "Marseille",
    "olympique lyonnais": "Lyon",
    "lyon": "Lyon",
    "ol": "Lyon",
    "as monaco": "Monaco",
    "monaco": "Monaco",
    "losc lille": "Lille",
    "lille": "Lille",
    "stade rennais fc": "Rennes",
    "rennes": "Rennes",
    "ogc nice": "Nice",
    "nice": "Nice",
    "rc lens": "Lens",
    "lens": "Lens",
    "stade brestois 29": "Brest",
    "brest": "Brest",
    "montpellier hsc": "Montpellier",
    "montpellier": "Montpellier",

    # International
    "argentina": "Argentina",
    "france": "France",
    "brazil": "Brazil",
    "brasil": "Brazil",
    "england": "England",
    "germany": "Germany",
    "deutschland": "Germany",
    "spain": "Spain",
    "españa": "Spain",
    "portugal": "Portugal",
    "netherlands": "Netherlands",
    "holland": "Netherlands",
    "belgium": "Belgium",
    "croatia": "Croatia",
    "morocco": "Morocco",
    "senegal": "Senegal",
    "japan": "Japan",
    "south korea": "South Korea",
    "usa": "United States",
    "united states": "United States",
    "united states of america": "United States",
}

_LOWER = {k.lower(): v for k, v in _ALIASES.items()}


def normalize_team_name(name: str) -> str:
    """Return canonical display name, or the original if not found."""
    key = name.lower().strip()
    return _LOWER.get(key, name)


def alias_key(name: str) -> str:
    """Return a lowercased, punctuation-stripped key for fuzzy matching."""
    s = name.lower().strip()
    s = re.sub(r"[^a-z0-9 ]", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s
